### ISSUE TITLE
화면구현 - 쇼핑몰 메인

### ISSUE THREAD

**Issue by dpgbdb** [ooo3345sjh/Kmarket2#6]
2023/02/09 쇼핑몰 메인 기능 구현 시작
2023/02/13 쇼핑몰 메인 기능 구현 작업중
2023/02/15 
2023/02/17 쇼핑몰 메인 이미지 구현

**Comment by asdeqqga** [comment]
- [x] 클릭시 메인 링크 이동
- [x] 상품검색
- [x] 상품 카테고리 메뉴
- [x] 슬라이드 배너
- [x] 베스트 상품
- [x] 히트 상품
- [x] 이미지 불러오기
- [x] index 헤더 
- [x] 카테고리 출력
