### ISSUE TITLE
기능구현 - 관리자/상품등록(admin/product/register)

### ISSUE THREAD

**Issue by dpgbdb** [ooo3345sjh/Kmarket2#8]
- [x] 상품 분류 카테고리 가져오기
- [x] 포인트는 상품 가격의 1% 자동 입력
- [x] 상품 등록 구현
- [x] 이미지는 크기에 맞춰 등록
- [x] 유효성 검사

**Comment by JinWooo96** [comment]
2023/02/16 상품 등록 기능 구현 완료
